// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Note: this installed Prisma version's config type only supports `url`
  // and `shadowDatabaseUrl` here (no `directUrl`) — migrations run through
  // the pooled connection, which works fine for this app's simple schema.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
